Enable CD Permissions on google-oauth-plugin
jenkinsci/google-oauth-plugin pull request #199
Opened 2023-10-10 10:12 UTC by julieheard

Hi, 

I am enabling automated releases in this repo to make it easier to ensure merged PRs make it into a new release in a timely fashion. I am following: https://www.jenkins.io/doc/developer/publishing/releasing-cd/

I also changed the incrementals version in this repo to be the newest version [here](https://github.com/jenkinsci/incrementals-tools).

If you are happy to enable CD in this plugin, please approve this PR. As part of the process of enabling CD, I will also make a PR on https://github.com/jenkins-infra/repository-permissions-updater and will link it [here] shortly. Could you also go to the linked PR and approve that as well.

Many thanks 😄 

```[tasklist]
### Submitter checklist
- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

2023-10-10 13:44 UTC, NotMyFault requested changes
The `<scm>` tag pattern should match `<tag>${scmTag}</tag>`

2023-10-10 13:44 UTC, NotMyFault commented on pom.xml
> +    <revision>0</revision>
```suggestion
    <revision>1</revision>
```
Using any number lower than 1, starts cutting releases considered older than 1.0.8

2023-10-10 13:44 UTC, NotMyFault commented on pom.xml
> +  <version>${revision}${changelist}</version>
```suggestion
  <version>${revision}.${changelist}</version>
```

2023-10-10 15:13 UTC, julieheard commented
Thank you for your help on this PR @NotMyFault, I really appreciate your time 🙂

2023-10-10 16:24 UTC, NotMyFault approved these changes

2023-10-11 15:20 UTC, rsandell requested changes

2023-10-11 15:20 UTC, rsandell commented on pom.xml
> +    <revision>1</revision>
```suggestion
    <revision>2</revision>
```

2023-10-11 15:22 UTC, rsandell commented on pom.xml
> +    <revision>1</revision>
I changed my mind, it is ok, since we never hit >= 1.1

2023-10-11 15:22 UTC, rsandell approved these changes

2023-10-11 15:23 UTC, merged

2023-10-11 15:25 UTC, rsandell commented
But it looks like you edited an old pom file? version  1.1.1 is the latest release.